#name, main, version and api are required
name: ELIASEMPRESAS
main: ELIASEMPRESAS\MainClass
src-namespace-prefix: ELIASEMPRESAS
version: 1.4.1+dev
api: 5.0.0

load: POSTWORLD
author: ELIAS EMPRESAS
description: Olá aqui é as Elias Empresas 
website: https://www.eliasempresas.com
commands:
  principal:
    description: Comando principal 
    usage: "/eliasempresas"
    permission: eliasempresas.command.principal
  curta:
    description: Comando principal forma curta
    usage: "/ee"
    permission: eliasempresas.command.curta
permissions:
  eliasempresas.command.principal:
    description: "Permite que o usuário execute o comando de principal"
    default: true
  eliasempresas.command.curto:
    description: "Permite que o usuário execute o comando de curto"
    default: true
